### ISSUE TITLE
超级冶炼炉的合金冶炼模式不工作  群里其他人也遇到了同样问题

### ISSUE THREAD

**Issue by yang-fu** [nutant233/GregTech-Leisure#117]
![image](https://github.com/user-attachments/assets/a220e8ed-2929-4616-8dc8-6af49101e8a7)

**Comment by Alderichr** [comment]
检查电路与原料  如果是样板总成 那他有时候就是会这样

**Comment by yang-fu** [comment]
用输入总线也是一样 并且群里也有其他人反应同样的问题

**Comment by yang-fu** [comment]
青铜不需要电路板
