### ISSUE TITLE
样板总成的液体催化剂栏位最多只能放8B  但是配方要求10B的催化剂

### ISSUE THREAD

**Issue by yang-fu** [nutant233/GregTech-Leisure#118]
![image](https://github.com/user-attachments/assets/932f2407-9c66-4e1e-9245-5d572d134f91)
![image](https://github.com/user-attachments/assets/6e552d41-cdc0-4eef-8f75-af66e2c04f98)

**Comment by Alderichr** [comment]
别的栏也可以放啊   不行你另外单独放一个ulv输入仓也行啊

**Comment by yang-fu** [comment]
好的
