### ISSUE TITLE
8级净化水的配方输出6格  但是蒸发塔做多只能做五层 

### ISSUE THREAD

**Issue by yang-fu** [nutant233/GregTech-Leisure#121]
![image](https://github.com/user-attachments/assets/9a3df5a3-3f5e-426e-981a-1231a45fb6a6)
![image](https://github.com/user-attachments/assets/93b12b3c-5633-42bc-b2ad-d74ffaa55b2b)
![image](https://github.com/user-attachments/assets/e16fe16a-f402-4dd3-bf08-5a04c994c9f2)
而且多重输出 输出仓 输出总成  me输出总成都无法成型  只能使用输出仓

**Comment by TangYishanE** [comment]
蒸发塔和蒸馏塔工作结构不同，不是每层输出一种产物，在与蒸发塔主方块同一层的位置放置有足够输出空间的me输出总成即可，这个问题我也遇到了，最低是5层，所以最少还要放置2个输出仓，这个我昨天才遇到了这个问题。如图所示，可以正常工作
![image](https://github.com/user-attachments/assets/62e58f63-d1b9-494c-91e1-ff6e0d0087d6)
