### ISSUE TITLE
冷却塔的2468格水需要手动倒吗

### ISSUE THREAD

**Issue by yang-fu** [nutant233/GregTech-Leisure#128]
![image](https://github.com/user-attachments/assets/fe9b744c-71ad-4b0a-b81f-132c834a43e4)
2468格水总不至于真用手倒入吧

**Comment by yang-fu** [comment]
好像可以先放冰 在挖成水

**Comment by TheDesiringOne** [comment]
可惜貌似没有mod可以调动me网络的流体进行大量放置。
