### ISSUE TITLE
化工厂进行胶原的合成时，若输出总线空间不足则导致游戏崩溃

### ISSUE THREAD

**Issue by Funtacs** [nutant233/GregTech-Leisure#138]
无私货测试：
化工厂配置：UHV输入/输出总线/仓，其中输出仓接me接口，输出总线闲置；渊狱合金线圈，无菌维护仓，uv无线能源仓，zpm并行控制仓。
现象：起初正常运行（1024并行），至uhv输出总线将满时运行一次256并行的配方，在该配方将结束时闪退。
另附该测试的崩溃报告。
[错误报告-2024-9-29_0.53.53.zip](https://github.com/user-attachments/files/17175616/-2024-9-29_0.53.53.zip)

**Comment by Funtacs** [comment]
补：版本为云盘最新版本1.4.3.0

**Comment by Oupaisuki** [comment]
为什么不用me输出总成，到这阶段了批发没问题吧
