### ISSUE TITLE
me无限硬盘更新后物品会丢失

### ISSUE THREAD

**Issue by yang-fu** [nutant233/GregTech-Leisure#139]

**Comment by nutant233** [comment]
打开原存档的disk_manager.dat，找到无限磁盘
<img>f1f38836d90274a474efe135d16052c3</img>然后把对应的整个2 entries复制，再打开新版本存档的disk_manager.dat，粘贴到disklist里面，再把数据tag中的ic改成count，amts改成amount

**Comment by SakiyoruSK** [comment]
没懂 能否有个视频演示
