### ISSUE TITLE
將翻譯鍵替換成正確的格式

### ISSUE THREAD

**Issue by EvanHsieh0415** [nutant233/GregTech-Leisure#14]
![圖片](https://github.com/user-attachments/assets/64d4c914-1daf-4a96-bf8b-21f3bd8ed8e9)
![圖片](https://github.com/user-attachments/assets/406a48c2-caa0-4a0e-b199-13cbd87bf1c2)

例如：在此處可將翻譯鍵設為 `dimension.minecraft.overworld.name`

**Comment by nutant233** [comment]
The rectification has been completed.
