### ISSUE TITLE
能切换编程电路有什么用

### ISSUE THREAD

**Issue by foxwhite25** [nutant233/GregTech-Leisure#143]
尝试了一下组装机用ae主动自动化，发现如果打开阻挡模式，因为样板里面也有编程电路会导致阻挡模式检测到机器里面也有一个虚拟电路，然后不发货；如果不打开阻挡模式多个电路就会串了。

**Comment by nutant233** [comment]
看看任务

**Comment by foxwhite25** [comment]
![image](https://github.com/user-attachments/assets/732b5bb6-5f76-48d8-89be-e982026e6590)
所以呢，只是说了能用，但是实际上ae自动化不能用

**Comment by foxwhite25** [comment]
@nutant233
