### ISSUE TITLE
对于可编程仓的拙劣模仿并不能用ae自动化

### ISSUE THREAD

**Issue by foxwhite25** [nutant233/GregTech-Leisure#144]
我知道输入电路板能够切换，但是你能不能看看为什么我说不能用。

如果打开阻挡模式，因为样板里面也有编程电路会导致阻挡模式检测到机器里面也有一个虚拟电路，然后不发货；如果不打开阻挡模式多个电路就会串了。

你要么搞一个其他物品，叫什么设定器，输入自动切换，要么修改ae的阻挡模式的运作方式，使其无视编程电路，现在这样根本没有任何用

**Comment by nutant233** [comment]
返回模式

**Comment by Alderichr** [comment]
设置阻挡返回模式  不把这个部件做完不发下一份材料

**Comment by foxwhite25** [comment]
这样会导致很严重的产能丢失，因为格雷机器是吃了物品工作的，阻挡模式可以使得上一个配方在合成的时候下一个配方已经预备在输入了，如果使用这种模式需要等配方完成并且自动输出下一个配方才能输入

**Comment by Alderichr** [comment]
一样的啊  就算是预输入也要等上一份做完才能做下一份  返回模式也要等上一份做完才会发下一份材料     或者你直接把样板翻倍就得了
