### ISSUE TITLE
gtm的配置不生效

### ISSUE THREAD

**Issue by Heng-ws** [nutant233/GregTech-Leisure#153]
感觉像是跟什么东西冲突了，单独装gtm是能生效的
![image](https://github.com/user-attachments/assets/0c14df0f-4999-4ff7-837c-c8adcb56b7d0)
![image](https://github.com/user-attachments/assets/dc4189e8-2f3c-44b6-b548-1968641b609e)

**Comment by nutant233** [comment]
https://github.com/nutant233/GTLCore/blob/94d1975f5237de79024c059eafbbdb8f5f7e0ccd/src/main/java/org/gtlcore/gtlcore/GTLGTAddon.java#L113
