### ISSUE TITLE
箱子和桶的组装机配方冲突

### ISSUE THREAD

**Issue by xingchen5996** [nutant233/GregTech-Leisure#162]
如题，即使在有控制电路的情况下在合成过程中也总会优先合成桶而不是箱子
多方块结构的组装机我还没有试过，但是应该也是同样的状况
![image](https://github.com/user-attachments/assets/6b8fc263-7bac-4f8a-b18c-99fc4e509268)
![image](https://github.com/user-attachments/assets/f6a81620-7b9e-48e3-9d15-2a98e242c545)
![image](https://github.com/user-attachments/assets/c2bc4027-22a6-4daf-8568-acdf64d14ae3)

**Comment by nutant233** [comment]
https://github.com/GregTechCEu/GregTech-Modern/issues/new/choose
