### ISSUE TITLE
解包机配方在jei自动填入AE合成面板时有概率出错

### ISSUE THREAD

**Issue by xingchen5996** [nutant233/GregTech-Leisure#164]
如图，复现方式：将合成格清空后直接点开JEI合成表中的转移物品按钮
![image](https://github.com/user-attachments/assets/14961b80-ed38-4e81-b69b-2e193118787b)
![image](https://github.com/user-attachments/assets/86b82333-a980-484b-9c5c-7d7e03b427cf)

**Comment by foxwhite25** [comment]
我也遇到了这问题，貌似不是概率而是打包机莫名其妙有个配方是解包机的配方，导致合成冲突了，并且砷化镓的配方必定需要解包

**Comment by foxwhite25** [comment]
![image](https://github.com/user-attachments/assets/027a88ec-dbe3-451f-9a97-148a99590c63)
装个Polymorph就可以解决配方冲突
