### ISSUE TITLE
易串的配方

### ISSUE THREAD

**Issue by nutant233** [nutant233/GregTech-Leisure#172]
使用任务列表，格式：
仅同编程电路，无编程电路与编程电路，不同编程之间的串不算
- [x] 配方类型 - 输出 - 输入 - 配方id（可选）- 和哪些串

**Comment by TTTTTiT** [comment]
组装机-输出：原版箱子-输入：木板、编程电路8-配方id-串木桶配方

**Comment by hcf0526** [comment]
闪电处理 - 输出：福禄伊克斯水晶 - 输入：1x红石粉，1x下界石英，1x赛特斯石英, 水1000 - 配方id：ae2:lightning_processor/fluix_crystal - 串充能赛特斯石英配方ae2:lightning_processor/charged_certus_quartz_crystal

**Comment by Oupaisuki** [comment]
化反-输出：苯乙烯-输入：苯 和乙烯 编程电路1 和氯苯串，会变成氯乙烯

**Comment by nutant233** [comment]
> 化反-输出：苯乙烯-输入：苯 和乙烯 编程电路1 和氯苯串，会变成氯乙烯
仅同编程电路

**Comment by Alderichr** [comment]
燃料精炼
输出：浓缩阱混合燃料
输入：碳粉/气态氢/气态氧/气态氮/过氧化氢
和火箭燃料（偏二甲并四氧化二氮）串  无编程电路
下单混合燃料容易变成火箭燃料四氧化二氮
