### ISSUE TITLE
锅炉界面丢失

### ISSUE THREAD

**Issue by KingPrimes** [nutant233/GregTech-Leisure#185]
青铜锅炉，钢锅炉界面显示状况
![image](https://github.com/user-attachments/assets/4748651c-fd93-4932-aae3-3a4c5d6fa9ed)
![image](https://github.com/user-attachments/assets/e3f487b4-ab44-4bb6-96c9-e2566a9c2025)

**Comment by nutant233** [comment]
去找gtm
