### ISSUE TITLE
关于输入总成吞材料的问题

### ISSUE THREAD

**Issue by duck-is-me** [nutant233/GregTech-Leisure#19]
当样板供应器贴输入总成然后下单时，可能会出现物品没了流体在输入总成里面的情况，前几天有个人的八台虚采还被吞了，这是一个巨大的问题，我认为应尽快修好。

**Comment by foxwhite25** [comment]
Related issues: https://github.com/EpimorphicPioneers/Gregic-Energistics/issues/32
