### ISSUE TITLE
Large Bronze Boiler UI is broken

### ISSUE THREAD

**Issue by MaGeBZz** [nutant233/GregTech-Leisure#191]
![image](https://github.com/user-attachments/assets/7b7904e0-fc5e-4dfb-82d7-1c1820204b6a)

**Comment by nutant233** [comment]
Wait for gtm to fix it

**Comment by MaGeBZz** [comment]
Yeah asked on the discord for gtm and they confirmed it's a known problem so it's up to them to fix it, will close this then!
