### ISSUE TITLE
Block placing NBT

### ISSUE THREAD

**Issue by MaGeBZz** [nutant233/GregTech-Leisure#194]
After you place a block all blocks seem to have NBT data
So even if you place stone bricks or bricks they won't stack with other ones
For some blocks like compressed chests that makes sense but for a lot of things it's really not necessary to have all of them getting NBT

**Comment by MaGeBZz** [comment]
Little note: not everything seems to have that problem but stone bricks and bricks are definetely, probably way more but deepslate for example doesn't have that problem

**Comment by MaGeBZz** [comment]
Why is it not in the pack if that could help?

**Comment by nutant233** [comment]
This was discovered a few days ago, and it's still uncertain whether it's useful.

**Comment by MaGeBZz** [comment]
Yeah even this mod will have some problems cause manual crafting with AE2 won't let you pull all items out
For example you wanna make bronze ingot with hammer to bronze plate then the system won't use all bronze ingots and mostly only what's in the crafting field itself
