### ISSUE TITLE
相同物品不同序列号

### ISSUE THREAD

**Issue by nyanmaid** [nutant233/GregTech-Leisure#197]
如图，存进AE的物品不知道为什么有两个序列号，自动合成的时候不同的序列号物品不通用。
许多锭都有此问题。我用的是github上的最新版本
![image](https://github.com/user-attachments/assets/3088756d-48f9-4ab4-8e19-65cf39179e4d)
![image](https://github.com/user-attachments/assets/966ef06c-cfea-4c58-9bc9-2c7782022545)

**Comment by nyanmaid** [comment]
![image](https://github.com/user-attachments/assets/c9d068c1-bcf5-45e3-8812-3faaeb26a189)
不知道是哪个mod给物品后面加了个空的tag，导致它们不通用了

**Comment by nyanmaid** [comment]
是压缩箱子。。。 gt的粉末或者锭啥的装里面然后打掉箱子再放置就会添加一个空tag

**Comment by Oupaisuki** [comment]
https://www.mcmod.cn/class/16787.html这个模组可以解决这个问题
