### ISSUE TITLE
真空泵似乎无效

### ISSUE THREAD

**Issue by SCAFprivate** [nutant233/GregTech-Leisure#202]
如图这是个生效的真空泵
![image](https://github.com/user-attachments/assets/59b5c0a7-caa7-4638-a261-8b8cf5705a83)
然后这里i这里贴个组装机也不干活
![GZD1B9FKLPBVV58$O Y_OOI](https://github.com/user-attachments/assets/82e52e20-270c-477b-8acb-da9b2820cd1b)
不知道是坏了还是用法有问题

**Comment by SCAFprivate** [comment]
![image](https://github.com/user-attachments/assets/85512297-2899-473e-9cc8-bcd2d1000361)

**Comment by SCAFprivate** [comment]
![image](https://github.com/user-attachments/assets/67e0fa61-bdd5-40cd-98e3-24e480405247)
如图，貌似并不是电压锁定的问题，组装机就在真空泵2格后面，用的lv配方也不能做真空管
![image](https://github.com/user-attachments/assets/f7879c15-f6ae-4074-bdb3-5d816329154b)

**Comment by SCAFprivate** [comment]
![image](https://github.com/user-attachments/assets/bab8854b-12c2-4823-a694-79dde46a3157)

**Comment by nutant233** [comment]
贴着
