### ISSUE TITLE
细菌培养缸不工作

### ISSUE THREAD

**Issue by nyanmaid** [nutant233/GregTech-Leisure#216]
![image](https://github.com/user-attachments/assets/f2bbedb6-181d-4553-b729-17eb3a281805)
![image](https://github.com/user-attachments/assets/3057fa33-27a0-4813-b1b9-f1d1a3b096bc)
![image](https://github.com/user-attachments/assets/9e370bf3-eace-4dfe-9d16-de7b4e0caf5a)
![image](https://github.com/user-attachments/assets/06e4b1aa-7d82-4952-a6ea-18c0018668a2)
![image](https://github.com/user-attachments/assets/d48351ab-cb8f-4ab6-abf8-c27626812993)

确认了合成表的所有元素都足够，但是不工作。
要求10Sv但是最低的杆都提供50Sv，不知道是不是这个问题

**Comment by nyanmaid** [comment]
测试了下应该是放射仓的问题，0Sv的能工作，10Sv的不行

**Comment by nyanmaid** [comment]
最新版也有这个问题

**Comment by nutant233** [comment]
![95b3fc88aa60adfd68246a8e15d735e4](https://github.com/user-attachments/assets/f1bad158-c74e-4022-b1f8-1ab07a287aa6)
0代表无需放射

**Comment by nyanmaid** [comment]
感谢，我搞错了抑制量。以为是设到10辐射剂量就是10. 
如果可能的话希望能在任务书或者方块上面添加以下描述。
