### ISSUE TITLE
ME输出总线怼到ME输入总线会崩端

### ISSUE THREAD

**Issue by nyanmaid** [nutant233/GregTech-Leisure#217]
AE的那个输出总线怼到GT的那个ME输入总线（不是库存总线），过一会儿会直接崩端

**Comment by nyanmaid** [comment]
[crash-2024-10-29_18.55.53-server.txt](https://github.com/user-attachments/files/17557105/crash-2024-10-29_18.55.53-server.txt)

**Comment by nutant233** [comment]
你应该找GTM，并且没人会这么做
