### ISSUE TITLE
当系统中物品超过2.1G时，库存输入总线无法为结构输入物品

### ISSUE THREAD

**Issue by ErYangHuaGao** [nutant233/GregTech-Leisure#234]
当系统中物品超过2.1G时，库存输入总线无法为结构输入物品
![image](https://github.com/user-attachments/assets/1a7a5994-9fae-47a8-b19c-5df2fc1350df)
![image](https://github.com/user-attachments/assets/1285d729-7c88-4370-a55c-d2cc7d2644b1)
推断问题是超过int上限后判断为负数了

**Comment by nutant233** [comment]
我修不了
