### ISSUE TITLE
大型蒸汽电路组装机多方块的BUG

### ISSUE THREAD

**Issue by 45vzdsg** [nutant233/GregTech-Leisure#30]
更新后大型蒸汽电路组装机不成形，不能用蒸汽的输入总线了；不消耗材料也会消耗，比如真空管

**Comment by gangzhengzhiwei** [comment]
能发图片吗？我这边没有复现

**Comment by 45vzdsg** [comment]
> 能发图片吗？我这边没有复现

现版本没有这个bug了，1.3.8.12没发布的时候在github下载更新的
