### ISSUE TITLE
超维度激光蚀刻成型检测导致游戏锁死

### ISSUE THREAD

**Issue by ChemEng227** [nutant233/GregTech-Leisure#33]
超维度激光蚀刻只有重启游戏后的短暂时间内可以正常成型，时间稍长（大约超过10min）一旦成型就立即导致游戏锁死（服务器无响应并连接超时）。

游戏出现锁死时服务器端的CPU和内存占用均处于正常水平。

**Comment by nutant233** [comment]
多方块检测问题，我无法修复
