### ISSUE TITLE
对于戴森球算力消耗减少的修改未生效

### ISSUE THREAD

**Issue by yao-sk** [nutant233/GregTech-Leisure#49]
1.4.0.1版本的emi中显示的戴森球每个模块的算力消耗为1，但实际测试每个模块依旧消耗4算力，新存档测试结果依旧如此。另外，戴森球在使用可配置自动维护仓进行发射模块时，在把耗时调整到一半的情况下，会消耗模块但并不增加模块发射次数

**Comment by nutant233** [comment]
已修复，如果需要可在github下载
