### ISSUE TITLE
关于蒸汽输入和输出总线的多方块结构显示问题。

### ISSUE THREAD

**Issue by TheDesiringOne** [nutant233/GregTech-Leisure#52]
不知为什么，在使用蒸汽输入或输出总线形成多方块结构时，总线活动的动画会闪烁不停，应该是bug，请求修复
![屏幕截图 2024-08-23 172452](https://github.com/user-attachments/assets/d4d021b6-c2a2-436c-b192-c9f962ee8b31)

**Comment by TheDesiringOne** [comment]
还看到有人反馈，我也贴一下
1.4.0.2版本更新,机器输出的流体无法用桶取出

**Comment by nutant233** [comment]
去找gtm

**Comment by TheDesiringOne** [comment]
啊，我还以为是整合包的问题，那好吧。
