### ISSUE TITLE
me样板总成在一个大机器上电路板会串。。。

### ISSUE THREAD

**Issue by Artina-atina** [nutant233/GregTech-Leisure#57]
比如大化反上面几个总成。。一个1号的一个24号的。。做24号的苯酚时会用1号的电路板做出来联苯粉。。。(1号那个仓里面没有东西）
我去gtm上面问。。他们说gtl的gtm是私人分支版他们不支持。。所以来这里问一下下。。。

**Comment by nutant233** [comment]
流体不支持隔离

**Comment by Artina-atina** [comment]
那请问后面会修改吗。。还是一直这样了呀。。。

**Comment by nutant233** [comment]
GTM会在未来加入流体隔离

**Comment by Artina-atina** [comment]
哦哦。。谢谢。。。
