### ISSUE TITLE
modern ae2 additions的多入口多出口样板P2P怎么创建频道

### ISSUE THREAD

**Issue by xinxinsuried** [nutant233/GregTech-Leisure#58]
不会用也没找到教程
有8台组装机，就是无电路。有2个样板供应器
怎么创建2对8的样板p2p网络？根据https://github.com/Monifactory/MAE2/wiki/Multi-P2P-Tunnels的方法试了，但我使不出来

**Comment by nutant233** [comment]
我也没用过，你应该去对应模组那边询问

**Comment by yang-fu** [comment]
兄弟 你找到怎么用了吗 我也没找到怎么创建2对8
