### ISSUE TITLE
MOD REDISTRIBUTION

### ISSUE THREAD

**Issue by screret** [nutant233/GregTech-Leisure#69]
Most developers don't like pack creators redistributing their mods as JAR files on github, as that takes away from the developers' revenue and downloads. Please use something like [packwiz](https://packwiz.infra.link/installation/) for building the modpack instead of having all the mod JAR files in `.minecraft/mods`. this may slow down development initially as you can't have all of the repository in a prism instance, but it'll be better in the long run if you ever want to release the modpack outside of github.

I have alerted FTB to this issue, and they, for example, do not like having their mods reuploaded.

P.S.
Please do not fork and redistribute a custom version of GT. make an addon mod and add your custom content to it. We (GTM team) have gotten many issues that are caused by your custom fork.

**Comment by nutant233** [comment]
The rectification has been completed.
