### ISSUE TITLE
关于工业屠宰机的bug

### ISSUE THREAD

**Issue by duck-is-me** [nutant233/GregTech-Leisure#7]
在服务器中，在开启实体生成时，玩家不在工业屠宰机附近时，可能是由于弱加载的缘故，工业屠宰机依然会生成生物，但并不会杀死生物。这就会导致实体堆积，当玩家一进入附近的区域，服务器会计算大量的实体碰撞，会引发多线程死锁，导致炸服。我在我玩的那个服务器里就遇到了这样的bug，最后是用nbt studio删除实体数据修好的。

**Comment by nutant233** [comment]
[gtceu-1.20.1-1.3.1.jar.zip](https://github.com/user-attachments/files/16343411/gtceu-1.20.1-1.3.1.jar.zip)
测试一下

**Comment by duck-is-me** [comment]
我们服主懒得换
