### ISSUE TITLE
请求将时间扭曲者独立出来

### ISSUE THREAD

**Issue by gusuruofan** [nutant233/GregTech-Leisure#70]
请问能否将时间扭曲者作为一个mod独立出来
或者在kubejs中单独创立有关文件，可以基于kubejs和gtceu独立运行
已经被gtl养叼了，其他包gt部分前期实在是太慢了，一个合成动辄五六百秒，有点受不了了，想要单独添加个时间扭曲者
真的拜托了

**Comment by nutant233** [comment]
const $GTCapabilityHelper = Java.loadClass("com.gregtechceu.gtceu.api.capability.GTCapabilityHelper")
const $ClipContext = Java.loadClass("net.minecraft.world.level.ClipContext")

ItemEvents.rightClicked("kubejs:time_twister", event => {
    if (!event.player.isFake() && event.player.isSteppingCarefully()) {
        var recipeLogic = getEyePositionRecipeLogic(event.level, event.player)
        if (recipeLogic != null && recipeLogic.isWorking()) {
                recipeLogic.setProgress(recipeLogic.getProgress() + 100)
        }
    }
})

function getEyePositionPos(level, player) {
    return level.clip(new $ClipContext(player.getEyePosition(1), player.getEyePosition(1).add(player.getViewVector(1).scale(5)), $ClipContext.Block.OUTLINE, $ClipContext.Fluid.NONE, player)).getBlockPos()
}

function getEyePositionRecipeLogic(level, player) {
    return $GTCapabilityHelper.getRecipeLogic(level, getEyePositionPos(level, player), null)
}

**Comment by gusuruofan** [comment]
十分感谢！
