### ISSUE TITLE
客户端1.4.0.5版本的拓展样板供应器UI打不开

### ISSUE THREAD

**Issue by NEFirefox** [nutant233/GregTech-Leisure#76]
是ExtendAE-1.1.12本体造成的，手动回退1.1.11版本正常
不报错，只在logs底下会显现这一行:
[Render thread/WARN] [net.minecraft.client.gui.screens.MenuScreens/]: Failed to create screen for menu type: ae2:ex_pattern_provider

**Comment by xinxinsuried** [comment]
我1.4.0.5打得开啊

**Comment by xinxinsuried** [comment]
1.1.12

**Comment by NEFirefox** [comment]
可能是旧版本gtl存档升级后出现的问题?
我和另外一位在升级版本(1.3->1405)后就打不开了，我在新存档测试也会打不开
不知道具体原因
