### ISSUE TITLE
进阶装配线效率与能源仓不符

### ISSUE THREAD

**Issue by SakiyoruSK** [nutant233/GregTech-Leisure#91]
使用两个64a uv能源仓 制作luv电动马达时只有6000eu的耗能 zpm马达24000 luv耗能 后换4单个64a 单个4a问题依然存在
![1](https://github.com/user-attachments/assets/1f785962-1be3-4e78-8f44-e59267a96c38)
![2](https://github.com/user-attachments/assets/7e17732c-64ad-4665-abde-9887522d8947)

**Comment by nutant233** [comment]
超频坏了，明天修
