### ISSUE TITLE
太空电梯模块显示没连接 但是太空电梯本身正常运行

### ISSUE THREAD

**Issue by yang-fu** [nutant233/GregTech-Leisure#92]
![image](https://github.com/user-attachments/assets/31a8d3f1-200e-4653-8cce-a5f3ea22a385)
![image](https://github.com/user-attachments/assets/d6cd24cc-6f16-41ba-9761-8b67a57c98f3)
太空电梯和采矿模块都是用创造和终端弄出来的

**Comment by nutant233** [comment]
更新到最新版
