### ISSUE TITLE
关于版本1.4.1.1存在的小问题与提议

### ISSUE THREAD

**Issue by HTorch** [nutant233/GregTech-Leisure#96]
### 问题

1. 存在蒸汽大机器仍会尝试以最大可能并行运行配方，若输出总线格不足则不会减少并行运行而是不运行配方的问题
2. 存在筛选出的晶体（破碎、有瑕、精致、无瑕）无法磨成小撮、小堆、复数粉的问题
3. 存在粉不能在2*2合成栏通过有序合成为小堆与小撮粉的问题
4. 存在一些原配方与上版本配方未删除的问题（如旅行权杖）
5. 由于没有changelog，出现了在尝试升级客户端版本时因部分容器容量调整导致如压缩箱子物品消失及超级缸流体消失等问题
6. 存在压缩箱子在同方向相邻放置会变成原版大箱子的问题

### 可能是问题的问题

任务书-科技等级-低压：电力高炉任务可能写反了任务边框和显示物品大小[![pAuJdJg.jpg](https://s21.ax1x.com/2024/09/15/pAuJdJg.jpg)](https://imgse.com/i/pAuJdJg)

### 提议

1. 加回远海鲸吞之桶与格雷机器流体槽的I/O功能
2. 加入锻铁锭的铁锭烧炼配方

**Comment by nutant233** [comment]
1,2,3均为GTM问题，其他已经修复与调整
