### ISSUE TITLE
进阶装配线依然有问题  没有超频

### ISSUE THREAD

**Issue by yang-fu** [nutant233/GregTech-Leisure#98]
![image](https://github.com/user-attachments/assets/423be1dd-1d9b-4157-bfc7-f63934fb7fc2)
![image](https://github.com/user-attachments/assets/0e0cfb70-39f0-4bbf-91e8-0ac23845daf4)

**Comment by nutant233** [comment]
![f1d4fa328eaf4305b2caa8add68215ba](https://github.com/user-attachments/assets/1eb78e23-9d01-4f2b-8529-dee76bcef3ab)
